language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 7
  - hhvm
  - hhvm-nightly
  
matrix:
  allow_failures:
    - php: 7
    - php: hhvm
    - php: hhvm-nightly

install: composer install --dev --no-interaction

script:
 - if [[ $TRAVIS_PHP_VERSION = '7' || $TRAVIS_PHP_VERSION = 'hhvm' || $TRAVIS_PHP_VERSION = 'hhvm-nightly' ]]; then PHPUNIT_FLAGS="--process-isolation"
 - mkdir -p build/logs
 - phpunit -v --configuration "phpunit.xml.dist" --coverage-clover build/logs/clover.xml $PHPUNIT_FLAGS

after_script:
 - php vendor/bin/coveralls -v
