language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm
  
matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm

install: composer install --dev --no-interaction
script: phpunit --configuration "Tests/Configuration.xml"

script:
 - mkdir -p build/logs
 - phpunit --configuration "Tests/Configuration.xml" --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v