language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm
  
matrix:
  allow_failures:
    - php: hhvm

install: composer install --dev --no-interaction

script:
 - mkdir -p build/logs
 - phpunit --configuration "phpunit.xml.dist" --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v